spring:
  rabbitmq:
    host: docker
    port: 5672
    username: admin
    password: xzixi
server:
  port: 8080
zookeeper:
  server: docker
  namespace: xzixi
  digest: xzixi:xzixi
  session-timeout-ms: 60000
  connection-timeout-ms: 15000
  max-retries: 3
  base-sleep-time-ms: 1000
